- name: "OS"
  debug: msg="{{ ansible_lsb }}"
- name: "Memory"
  debug: msg="{{ ansible_memory_mb }}"
- name: "CPU"
  debug: msg="{{ansible_processor}}"
- name: "AppArmor status"
  debug: msg="{{ansible_apparmor}}"
- name: "Process status"
  command: ps aux | grep -Ev "(*sh|\[.*\]|*tty|*ansible)"
  register: ps_result
- debug: var=ps_result.stdout_lines
- name: "tree -L 3"
  command: tree -L 3 /home/isucon
  register: ls_result
- debug: var=ls_result.stdout_lines
- name: "ls /etc/systemd/system"
  command: ls /etc/systemd/system
  register ls_systemd_result
- debug: var=ls_systemd_result.stdout_lines
