- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - tree
    - vim-nox
    - dstat
    - tmux
    - unzip
    - zsh
    - python-mysqldb
    - git
    - mysql-server
    - mysql-client
    - nginx
    - vim