- name: Install packages for Ubuntu
  when: "ansible_distribution == 'Ubuntu'"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - tree
    - vim-nox
    - dstat
    - tmux
    - unzip
    - zsh
    - python-mysqldb
    - git
    - mysql-server
    - mysql-client
    - nginx
    - vim

- name: Install packages for CentOS
  when: "ansible_distribution == 'CentOS'"
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - tree
    - dstat
    - tmux
    - unzip
    - zsh
    - git
    - mariadb-server
    - nginx
    - htop
