- name: "Check version"
  command: nginx -V
  register: nginx_version
- debug: var=nginx_version.stderr_lines

- name: "create kataribe dir"
  become: no
  file:
    path: ~/kataribe
    state: directory

- name: "Download kataribe"
  become: no
  unarchive:
    src: https://github.com/matsuu/kataribe/releases/download/v0.3.0/linux_amd64.zip
    dest: ~/kataribe
    remote_src: yes
